### ISSUE TITLE
no connection to SAIC/MG anymore

### ISSUE THREAD

**Issue by Markus0806** [SAIC-iSmart-API/saic-java-client#120]
Since August 8, 2024, the gateway can no longer establish a connection to MG (SAIC).
The following error message is in the log file:

java[1425]: org.apache.hc.client5.http.ClientProtocolException: Unexpected response status: 429
java[1425]:         at net.heberling.ismart.Client.lambda$sendRequest$0(Client.java:37)
java[1425]:         at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
java[1425]:         at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
java[1425]:         at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
java[1425]:         at net.heberling.ismart.Client.sendRequest(Client.java:40)
java[1425]:         at net.heberling.ismart.mqtt.SaicMqttGateway.call(SaicMqttGateway.java:264)
java[1425]:         at net.heberling.ismart.mqtt.SaicMqttGateway.call(SaicMqttGateway.java:67)
java[1425]:         at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
java[1425]:         at picocli.CommandLine.access$1500(CommandLine.java:148)
java[1425]:         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
java[1425]:         at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
java[1425]:         at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
java[1425]:         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
java[1425]:         at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
java[1425]:         at picocli.CommandLine.execute(CommandLine.java:2170)
java[1425]:         at net.heberling.ismart.mqtt.SaicMqttGateway.main(SaicMqttGateway.java:395)
systemd[1]: saic-mqtt-gateway.service: Main process exited, code=exited, status=1/FAILURE

**Comment by villingerh** [comment]
I have the same issue. Trying the following URL in a browser gives me "Blocked by Sentinel (flow limiting)" 

https://tap-eu.soimt.com/TAP.Web/ota.mpv30

The Android Phone app still works

**Comment by gitHost7** [comment]
i have exact the same problem since days... any hints / solutions available ?

Ove

**Comment by gitHost7** [comment]
@Markus0806 and @villingerh : did you resolve this issue ?

**Comment by Markus0806** [comment]
I couldn't solve it with saic-java-client.
I'm using saic-python-mqtt-gateway now. 
Installed it in a docker and it works fine

**Comment by villingerh** [comment]
I also changed to saic-python-mqtt-gateway and used the oportunity to move it into my smal kubernetes setup.
But I am not yet finished with my overall setup, because the gateway sometimes misses to record if our MG5 is used.
